import React,{useEffect,useMemo,useState} from 'react';
import {HOURLY_RATE,DAYS_ES,RESTAURANT_ID,copyText,dayName,durationText,isoDate,mondayOf,money,pairClockRecords,scheduleForEmployee,scheduledMinutes,slotBounds,weekIdFor} from './peopleUtils';

export default function PeoplePortal({supabase,Brand}){
 const[employee,setEmployee]=useState(null),[employees,setEmployees]=useState([]),[employeeId,setEmployeeId]=useState(''),[pin,setPin]=useState(''),[showPin,setShowPin]=useState(false),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{loadEmployees()},[]);
 async function loadEmployees(){if(!supabase){setMsg('No hay conexión con el sistema.');return}const{data,error}=await supabase.from('employees').select('id,name,active,can_clock,pin').eq('active',true).eq('can_clock',true).order('name');if(error){setMsg('No se pudo cargar la plantilla.');return}setEmployees(data||[])}
 async function login(){if(!employeeId)return setMsg('Selecciona tu nombre.');if(!pin.trim())return setMsg('Introduce tu PIN.');setBusy(true);setMsg('Comprobando acceso…');const{data,error}=await supabase.from('employees').select('*').eq('id',employeeId).eq('active',true).maybeSingle();setBusy(false);if(error||!data||String(data.pin??'').trim()!==pin.trim())return setMsg('Nombre o PIN incorrecto. Revisa los datos o avisa a gerencia.');setEmployee(data);setMsg('')}
 if(!employee)return <main className="peopleLogin peopleLoginV2"><section className="peopleLoginShell"><header className="peopleLoginBrand"><img src="/colibri-people-mark.png" alt="Colibrí"/><div><h1>Colibrí <span>People</span></h1><p>Brasería El Colibrí</p></div></header><div className="peopleCard peopleLoginCard"><span className="peopleEyebrow">PORTAL DEL EMPLEADO</span><h2>Tu jornada, en un solo sitio</h2><p className="peopleLoginIntro">Ficha tu entrada y salida, consulta tus horas y revisa tu semana desde el móvil.</p><label><span>Empleado</span><select value={employeeId} onChange={e=>{setEmployeeId(e.target.value);setMsg('')}}><option value="">Selecciona tu nombre</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label><span>PIN personal</span><div className="peoplePinField"><input type={showPin?'text':'password'} inputMode="numeric" autoComplete="current-password" placeholder="Introduce tu PIN" value={pin} onChange={e=>{setPin(e.target.value.replace(/\D/g,''));setMsg('')}} onKeyDown={e=>e.key==='Enter'&&login()}/><button type="button" aria-label={showPin?'Ocultar PIN':'Mostrar PIN'} onClick={()=>setShowPin(v=>!v)}>{showPin?'Ocultar':'Ver'}</button></div></label><button className="peopleLoginSubmit" onClick={login} disabled={busy}>{busy?'Entrando…':'Entrar en Mi Jornada'}</button>{msg&&<p className="peopleMessage">{msg}</p>}<div className="peopleLoginHelp"><b>Tu PIN es personal</b><span>No lo compartas. Puedes cambiarlo dentro de tu perfil.</span></div></div><footer>Colibrí People · Control horario seguro</footer></section></main>;
 return <EmployeeHome supabase={supabase} employee={employee} onLogout={()=>{setEmployee(null);setPin('')}}/>;
}

function EmployeeHome({supabase,employee,onLogout}){
 const[tab,setTab]=useState('jornada'),[rows,setRows]=useState([]),[scheduleRow,setScheduleRow]=useState(null),[requests,setRequests]=useState([]),[loading,setLoading]=useState(true),[msg,setMsg]=useState(''),[now,setNow]=useState(new Date());
 const monday=mondayOf(),from=isoDate(monday),to=isoDate(new Date(monday.getTime()+7*86400000)),weekId=weekIdFor();
 useEffect(()=>{load();const t=setInterval(()=>setNow(new Date()),30000);return()=>clearInterval(t)},[]);
 async function load(){setLoading(true);const[{data:r},{data:s},{data:q}]=await Promise.all([
  supabase.from('clock_records').select('*').or(`employee_id.eq.${employee.id},employee_name.eq.${employee.name}`).gte('created_at',from+'T00:00:00').lt('created_at',to+'T00:00:00').order('created_at'),
  supabase.from('work_schedule_weeks').select('*').eq('restaurant_id',RESTAURANT_ID).eq('week_id',weekId).maybeSingle(),
  supabase.from('employee_time_requests').select('*').eq('employee_id',employee.id).order('created_at',{ascending:false}).limit(20)
 ]);setRows(r||[]);setScheduleRow(s||null);setRequests(q||[]);setLoading(false)}
 const pairs=useMemo(()=>pairClockRecords(rows),[rows,now]);const schedule=useMemo(()=>scheduleForEmployee(scheduleRow,employee),[scheduleRow,employee]);
 const latest=rows[rows.length-1],working=String(latest?.type||'').toLowerCase()==='entrada';
 const totalMinutes=Object.values(pairs).flat().reduce((a,x)=>a+x.minutes,0);const planned=scheduledMinutes(schedule);const pending=requests.filter(x=>x.status==='pending');
 const validatedMinutes=Object.entries(pairs).reduce((sum,[date,ps])=>{const actual=ps.reduce((a,x)=>a+x.minutes,0);const day=dayName(date+'T12:00:00');const dailyPlanned=scheduledMinutes({[day]:schedule[day]||[]});const approved=requests.some(r=>r.status==='approved'&&isoDate(r.proposed_at)===date);return sum+(approved?actual:dailyPlanned?Math.min(actual,dailyPlanned):0)},0);
 const todayName=dayName(new Date()),todayBounds=slotBounds(schedule[todayName]||[]);const todayPairs=pairs[isoDate(new Date())]||[];
 async function clock(type,method='gps'){
  setMsg('Comprobando ubicación...');let coords=null;if(method==='gps'){try{coords=await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{enableHighAccuracy:true,timeout:15000}));}catch{return setMsg('No se pudo obtener el GPS. Usa el QR del local.')}}
  const note=type==='salida'&&todayBounds&&new Date().toTimeString().slice(0,5)>todayBounds.end?prompt('Has superado el horario previsto. Escribe el motivo para que el gerente pueda revisarlo:','')||'': '';
  const{data,error}=await supabase.rpc('registrar_fichaje_v2',{p_employee_name:employee.name,p_pin:employee.pin,p_type:type,p_note:note,p_gps_lat:coords?.coords?.latitude||null,p_gps_lng:coords?.coords?.longitude||null,p_accuracy:coords?.coords?.accuracy||null,p_method:method});
  if(error||!data?.ok){setMsg('No se pudo fichar: '+(error?.message||data?.message||'revisa el GPS o usa QR'));return}
  if(type==='salida'&&note){await supabase.from('employee_time_requests').insert({employee_id:employee.id,employee_name:employee.name,request_type:'overtime',proposed_at:new Date().toISOString(),reason:note,status:'pending'});setMsg('Salida registrada. El tiempo fuera del cuadrante queda pendiente de validación.')}else setMsg(type==='entrada'?'Entrada registrada correctamente. ¡Buen turno!':'Salida registrada. Tu resumen ya está actualizado.');await load();
 }
 async function requestForgottenExit(){const open=[...rows].reverse().find(r=>String(r.type).toLowerCase()==='entrada');if(!open)return setMsg('No encontramos una entrada abierta esta semana.');const proposed=prompt('Indica la fecha y hora real de salida (AAAA-MM-DD HH:MM)',`${isoDate(new Date())} ${new Date().toTimeString().slice(0,5)}`);if(!proposed)return;const reason=prompt('Cuéntanos brevemente qué ocurrió.','Se me olvidó fichar al salir.');if(!reason)return;const{error}=await supabase.from('employee_time_requests').insert({employee_id:employee.id,employee_name:employee.name,request_type:'forgotten_exit',related_clock_id:open.id,proposed_at:new Date(proposed.replace(' ','T')).toISOString(),reason,status:'pending'});if(error)return setMsg(error.message);setMsg('Solicitud enviada. Tu encargado la revisará.');load()}
 async function shareWeek(){let text=`*Mi resumen semanal · ${employee.name}*\n`;for(let i=0;i<7;i++){const d=new Date(monday);d.setDate(d.getDate()+i);const key=isoDate(d),mins=(pairs[key]||[]).reduce((a,x)=>a+x.minutes,0);text+=`${DAYS_ES[i]}: ${durationText(mins)}${(pairs[key]||[]).some(x=>!x.exit)?' (jornada abierta)':''}\n`}text+=`\nTotal fichado: *${durationText(totalMinutes)}*\nHoras previstas: ${durationText(planned)}\nEstimación validada: ${money(validatedMinutes/60*HOURLY_RATE)}`;await copyText(text);setMsg('Resumen copiado. Ya puedes pegarlo en WhatsApp.')}
 async function changePin(){const current=prompt('Introduce tu PIN actual');if(current!==String(employee.pin))return setMsg('El PIN actual no coincide.');const next=prompt('Nuevo PIN (4 a 8 números)');if(!/^\d{4,8}$/.test(next||''))return setMsg('El PIN debe tener entre 4 y 8 números.');const{error}=await supabase.rpc('employee_change_own_pin',{p_employee_id:employee.id,p_current_pin:current,p_new_pin:next});if(error)return setMsg(error.message);employee.pin=next;setMsg('PIN cambiado correctamente.')}
 async function enableReminders(){if(!('Notification'in window))return setMsg('Este móvil no admite notificaciones web.');const p=await Notification.requestPermission();if(p==='granted'){localStorage.setItem('colibriPeopleNotifications','1');new Notification('Colibrí People',{body:'Recordatorios activados. Te ayudaremos a no olvidar tus fichajes.'});setMsg('Recordatorios activados. Para mayor fiabilidad, añade esta web a la pantalla de inicio.')}else setMsg('No se han autorizado las notificaciones.')}
 const difference=totalMinutes-planned;const punctual=rows.filter(r=>r.type==='entrada').length?Math.max(0,100-Math.min(40,rows.filter(r=>r.type==='entrada'&&r.note).length*5)):100;
 return <main className="peopleApp"><header className="peopleHeader"><div className="peopleHeaderBrand"><img src="/colibri-people-mark.png" alt="Colibrí"/><div><span>COLIBRÍ PEOPLE</span><h1>Hola, {employee.name} 👋</h1><p>{working?'Tu jornada está en marcha.':'Todo listo para tu próxima jornada.'}</p></div></div><button onClick={onLogout}>Salir</button></header>
 <nav className="peopleTabs">{[['jornada','Mi jornada'],['semana','Mi semana'],['evolucion','Mi evolución'],['perfil','Mi perfil']].map(x=><button className={tab===x[0]?'active':''} onClick={()=>setTab(x[0])} key={x[0]}>{x[1]}</button>)}</nav>
 {msg&&<div className="peopleNotice">{msg}</div>}{loading?<div className="peopleCard">Cargando tus datos...</div>:<>
 {tab==='jornada'&&<div className="peopleGrid"><section className={'peopleCard peopleHero '+(working?'working':'')}><span>{working?'🟢 JORNADA INICIADA':'☀️ MI JORNADA'}</span><h2>{working?durationText(Math.round((now-new Date(latest.created_at))/60000)):'Aún no has fichado hoy'}</h2><p>Horario previsto: <b>{todayBounds?`${todayBounds.start} → ${todayBounds.end}`:'Sin turno asignado'}</b></p><div className="peopleActions"><button onClick={()=>clock('entrada')}>Fichar entrada GPS</button><button className="danger" onClick={()=>clock('salida')}>Fichar salida GPS</button></div><div className="peopleActions secondary"><button onClick={()=>clock('entrada','qr')}>Entrada QR</button><button onClick={()=>clock('salida','qr')}>Salida QR</button></div><button className="peopleLink" onClick={requestForgottenExit}>¿Olvidaste fichar la salida?</button></section>
 <section className="peopleCard"><h3>Esta semana</h3><div className="peopleMetric"><b>{durationText(totalMinutes)}</b><span>de {durationText(planned)} previstas</span></div><div className="peopleProgress"><i style={{width:`${Math.min(100,planned?totalMinutes/planned*100:0)}%`}}/></div><p className={Math.abs(difference)<=15?'positive':difference>0?'warning':'info'}>{Math.abs(difference)<=15?'👍 Vas perfecto con tu cuadrante':difference>0?`Llevas ${durationText(difference)} sobre lo previsto. Solo contará si se valida.`:`Te faltan ${durationText(-difference)} para completar lo previsto.`}</p></section>
 <section className="peopleCard"><h3>Estimación semanal</h3><div className="peopleMetric"><b>{money(validatedMinutes/60*HOURLY_RATE)}</b><span>{durationText(validatedMinutes)} × {money(HOURLY_RATE)}/h</span></div><small>Orientación basada en horas registradas. Las incidencias y extras necesitan validación.</small></section></div>}
 {tab==='semana'&&<section className="peopleCard"><div className="peopleTitleRow"><div><h2>Mi semana</h2><p>Tu resumen claro, día a día.</p></div><button onClick={shareWeek}>Copiar para WhatsApp</button></div><div className="peopleDays">{DAYS_ES.map((day,i)=>{const d=new Date(monday);d.setDate(d.getDate()+i);const p=pairs[isoDate(d)]||[],mins=p.reduce((a,x)=>a+x.minutes,0),bounds=slotBounds(schedule[day]||[]);return <article key={day}><div><b>{day}</b><small>{bounds?`${bounds.start}–${bounds.end}`:'Libre'}</small></div><strong>{durationText(mins)}</strong><span>{p.some(x=>!x.exit)?'🟡 Abierta':mins?'✅':'—'}</span></article>})}</div><div className="peopleTotals"><span>Total <b>{durationText(totalMinutes)}</b></span><span>Previstas <b>{durationText(planned)}</b></span><span>Pendientes <b>{pending.length}</b></span></div></section>}
 {tab==='evolucion'&&<div className="peopleGrid"><section className="peopleCard"><h2>Mi evolución</h2><div className="peopleStats"><div><b>{punctual}%</b><span>Puntualidad</span></div><div><b>{Object.values(pairs).filter(x=>x.some(p=>p.exit)).length}</b><span>Jornadas completas</span></div><div><b>{requests.length}</b><span>Solicitudes</span></div><div><b>{planned?Math.round(totalMinutes/planned*100):0}%</b><span>Horas del cuadrante</span></div></div><p className="positive">Tus datos te ayudan a tener siempre claro tu trabajo y tus horas.</p></section><section className="peopleCard"><h3>Mis solicitudes</h3>{requests.length?requests.map(r=><div className="peopleRequest" key={r.id}><b>{r.request_type==='forgotten_exit'?'Salida olvidada':'Regularización'}</b><span>{new Date(r.proposed_at).toLocaleString('es-ES')}</span><em className={r.status}>{r.status==='pending'?'En revisión':r.status==='approved'?'Aprobada':'Rechazada'}</em></div>):<p>No tienes solicitudes. Todo está en orden.</p>}</section></div>}
 {tab==='perfil'&&<div className="peopleGrid"><section className="peopleCard"><h2>Mi perfil</h2><p><b>{employee.name}</b></p><p>PIN personal: ••••</p><button onClick={changePin}>Cambiar mi PIN</button><p><small>Tu gerente puede ayudarte a restablecerlo si lo olvidas.</small></p></section><section className="peopleCard"><h3>Recordatorios</h3><p>Activa avisos para recordar la entrada y la salida.</p><button onClick={enableReminders}>Activar notificaciones</button><small>En iPhone, añade la web a la pantalla de inicio para recibir notificaciones compatibles con PWA.</small></section></div>}
 </>}</main>
}
