import React,{useEffect,useMemo,useState} from 'react';
import {HOURLY_RATE,RESTAURANT_ID,downloadCsv,durationMinutes,durationText,isoDate,mondayOf,money,pairClockRecords,scheduleForEmployee,scheduledMinutes,weekIdFor} from './peopleUtils';

export function EmployeeManagement({supabase,colors=[]}){
 const[employees,setEmployees]=useState([]),[form,setForm]=useState({name:'',pin:'',role:'empleado'}),[msg,setMsg]=useState('');useEffect(()=>{load()},[]);
 async function load(){const{data,error}=await supabase.from('employees').select('*').order('active',{ascending:false}).order('name');if(error)setMsg(error.message);setEmployees(data||[])}
 async function add(){if(!form.name.trim())return setMsg('Indica el nombre.');const pin=form.pin||String(Math.floor(1000+Math.random()*9000));const{error}=await supabase.from('employees').insert({name:form.name.trim(),pin,role:form.role,color:colors[employees.length%colors.length]||'#6b5b95',can_clock:true,active:true});if(error)return setMsg(error.message);setForm({name:'',pin:'',role:'empleado'});setMsg(`Empleado creado. PIN: ${pin}`);load()}
 async function patch(e,p){const{error}=await supabase.from('employees').update(p).eq('id',e.id);if(error)return setMsg(error.message);load()}
 async function changePin(e){const pin=prompt(`Nuevo PIN para ${e.name}`,String(e.pin||''));if(pin===null)return;if(pin&&!/^\d{4,8}$/.test(pin))return setMsg('El PIN debe tener entre 4 y 8 números.');await patch(e,{pin:pin||null,pin_enabled:Boolean(pin)});setMsg(pin?`PIN actualizado para ${e.name}`:`PIN eliminado para ${e.name}`)}
 async function generate(e){const p=String(Math.floor(1000+Math.random()*9000));await patch(e,{pin:p,pin_enabled:true});setMsg(`Nuevo PIN de ${e.name}: ${p}`)}
 return <div><div className="card peopleAdminHero"><div><span>COLIBRÍ PEOPLE</span><h2>Empleados y accesos</h2><p>Alta, baja, PIN y acceso al fichaje desde un único lugar.</p></div></div>{msg&&<div className="peopleNotice">{msg}</div>}<div className="card"><h3>Dar de alta un empleado</h3><div className="peopleFormRow"><input placeholder="Nombre" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="PIN (opcional)" inputMode="numeric" value={form.pin} onChange={e=>setForm({...form,pin:e.target.value})}/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="empleado">Empleado</option><option value="encargado">Encargado</option><option value="gerencia">Gerencia</option></select><button onClick={add}>Crear empleado</button></div></div><div className="peopleEmployeeList">{employees.map(e=><article className={'card peopleEmployee '+(!e.active?'inactive':'')} key={e.id}><div className="peopleEmployeeMain"><span className="sq" style={{background:e.color||'#6b5b95'}}/><div><h3>{e.name}</h3><p>{e.role||'Empleado'} · {e.active?'Activo':'Baja'}</p></div></div><div className="peoplePin"><span>PIN visible para gerencia</span><b>{e.pin_enabled===false||!e.pin?'Sin PIN':e.pin}</b></div><div className="peopleEmployeeActions"><button onClick={()=>changePin(e)}>Cambiar / eliminar PIN</button><button onClick={()=>generate(e)}>Generar PIN</button><button onClick={()=>patch(e,{can_clock:!e.can_clock})}>{e.can_clock?'Bloquear fichaje':'Permitir fichaje'}</button><button className={e.active?'red':''} onClick={()=>patch(e,{active:!e.active,terminated_at:e.active?new Date().toISOString():null})}>{e.active?'Dar de baja':'Reactivar'}</button></div></article>)}</div></div>
}

export function PeopleControlCenter({supabase}){
 const[employees,setEmployees]=useState([]),[rows,setRows]=useState([]),[requests,setRequests]=useState([]),[scheduleRow,setScheduleRow]=useState(null),[filter,setFilter]=useState('all'),[msg,setMsg]=useState('');
 const monday=mondayOf(),from=isoDate(monday),to=isoDate(new Date(monday.getTime()+7*86400000));useEffect(()=>{load();const t=setInterval(load,30000);return()=>clearInterval(t)},[]);
 async function load(){const[{data:e},{data:r},{data:q},{data:s}]=await Promise.all([supabase.from('employees').select('*').order('name'),supabase.from('clock_records').select('*').gte('created_at',from+'T00:00:00').lt('created_at',to+'T00:00:00').order('created_at'),supabase.from('employee_time_requests').select('*').order('created_at',{ascending:false}).limit(200),supabase.from('work_schedule_weeks').select('*').eq('restaurant_id',RESTAURANT_ID).eq('week_id',weekIdFor()).maybeSingle()]);setEmployees(e||[]);setRows(r||[]);setRequests(q||[]);setScheduleRow(s||null)}
 const summaries=useMemo(()=>employees.map(emp=>{const er=rows.filter(r=>String(r.employee_id)===String(emp.id)||r.employee_name===emp.name),pairs=pairClockRecords(er),worked=Object.values(pairs).flat().reduce((a,x)=>a+x.minutes,0),empSchedule=scheduleForEmployee(scheduleRow,emp),planned=scheduledMinutes(empSchedule),latest=er[er.length-1],working=String(latest?.type||'').toLowerCase()==='entrada',pending=requests.filter(x=>x.employee_id===emp.id&&x.status==='pending'),approved=requests.filter(x=>x.employee_id===emp.id&&x.status==='approved'),validated=Object.entries(pairs).reduce((sum,[date,ps])=>{const actual=ps.reduce((a,x)=>a+x.minutes,0);const day=new Date(date+'T12:00:00').toLocaleDateString('es-ES',{weekday:'long'});const label=day.charAt(0).toUpperCase()+day.slice(1);const dailyPlanned=scheduledMinutes({[label]:empSchedule[label]||[]});const ok=approved.some(r=>isoDate(r.proposed_at)===date);return sum+(ok?actual:dailyPlanned?Math.min(actual,dailyPlanned):0)},0);return{emp,er,pairs,worked,validated,planned,working,pending,pay:validated/60*HOURLY_RATE}}),[employees,rows,requests,scheduleRow]);
 async function decide(req,status){let proposed=req.proposed_at;if(status==='approved'&&req.request_type==='forgotten_exit'){const{error}=await supabase.from('clock_records').insert({employee_id:req.employee_id,employee_name:req.employee_name,type:'salida',method:'approved_manual',inside_radius:false,note:`REGULARIZACIÓN APROBADA · ${req.reason}`,created_at:proposed});if(error)return setMsg(error.message)}const{error}=await supabase.from('employee_time_requests').update({status,reviewed_at:new Date().toISOString(),manager_note:status==='approved'?'Aprobada por gerencia':'Rechazada por gerencia'}).eq('id',req.id);if(error)return setMsg(error.message);setMsg(status==='approved'?'Solicitud aprobada':'Solicitud rechazada');load()}
 function exportEmployee(s){const days=Object.entries(s.pairs).map(([date,p])=>[date,p[0]?.entry?.created_at?new Date(p[0].entry.created_at).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'}):'',p[p.length-1]?.exit?.created_at?new Date(p[p.length-1].exit.created_at).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'}):'',durationText(p.reduce((a,x)=>a+x.minutes,0))]);downloadCsv(`Horas_${s.emp.name}_${from}.csv`,[['Empleado',s.emp.name],['Semana',from,to],['Horas fichadas',durationText(s.worked)],['Horas validadas',durationText(s.validated)],['Horas cuadrante',durationText(s.planned)],['Estimación',money(s.pay)],[],['Fecha','Entrada','Salida','Total'],...days])}
 async function whats(s){const text=`*Horas validadas · ${s.emp.name}*\nSemana ${from}\nFichadas: ${durationText(s.worked)}\nValidadas: ${durationText(s.validated)}\nCuadrante: ${durationText(s.planned)}\nDiferencia: ${durationText(Math.abs(s.worked-s.planned))} ${s.worked>=s.planned?'sobre':'por debajo'}\nEstimación: ${money(s.pay)}`;await navigator.clipboard.writeText(text);setMsg('Resumen copiado para WhatsApp.')}
 const visible=summaries.filter(s=>filter==='all'||(filter==='working'&&s.working)||(filter==='pending'&&s.pending.length)||(filter==='inactive'&&!s.emp.active));const pendingAll=requests.filter(r=>r.status==='pending');
 return <div><div className="card peopleAdminHero"><div><span>CENTRO DE MANDO</span><h2>Personal en tiempo real</h2><p>Horas, cuadrante, incidencias y coste estimado.</p></div><button onClick={load}>Actualizar</button></div>{msg&&<div className="peopleNotice">{msg}</div>}<div className="peopleKpis"><div className="card"><span>Trabajando</span><b>{summaries.filter(x=>x.working).length}</b></div><div className="card"><span>Solicitudes</span><b>{pendingAll.length}</b></div><div className="card"><span>Horas semana</span><b>{durationText(summaries.reduce((a,x)=>a+x.worked,0))}</b></div><div className="card"><span>Coste estimado</span><b>{money(summaries.reduce((a,x)=>a+x.pay,0))}</b></div></div>
 {pendingAll.length>0&&<section className="card"><h2>Solicitudes pendientes</h2>{pendingAll.map(r=><article className="peopleApproval" key={r.id}><div><b>{r.employee_name}</b><span>Salida propuesta: {new Date(r.proposed_at).toLocaleString('es-ES')}</span><p>“{r.reason}”</p></div><div><button onClick={()=>decide(r,'approved')}>Aprobar</button><button className="red" onClick={()=>decide(r,'rejected')}>Rechazar</button></div></article>)}</section>}
 <div className="peopleFilters">{[['all','Todos'],['working','Trabajando'],['pending','Con pendientes'],['inactive','Bajas']].map(x=><button className={filter===x[0]?'active':''} onClick={()=>setFilter(x[0])} key={x[0]}>{x[1]}</button>)}</div><div className="peopleEmployeeList">{visible.map(s=><article className="card peopleEmployee" key={s.emp.id}><div className="peopleEmployeeMain"><span className="sq" style={{background:s.emp.color||'#6b5b95'}}/><div><h3>{s.emp.name}</h3><p>{s.working?'🟢 Trabajando':'⚪ Fuera'} · {s.pending.length} pendientes</p></div></div><div className="peopleMetricsInline"><span>Validadas <b>{durationText(s.validated)}</b></span><span>Cuadrante <b>{durationText(s.planned)}</b></span><span>Diferencia <b className={s.validated>s.planned?'warning':'positive'}>{s.validated>=s.planned?'+':''}{durationText(Math.abs(s.validated-s.planned))}</b></span><span>Estimación <b>{money(s.pay)}</b></span></div><div className="peopleEmployeeActions"><button onClick={()=>exportEmployee(s)}>Excel</button><button onClick={()=>whats(s)}>WhatsApp</button></div></article>)}</div></div>
}
