-- COLIBRÍ ERP PRO · RC 4.0 · COLIBRÍ PEOPLE
-- Ejecutar una vez en Supabase SQL Editor.

begin;

alter table if exists public.employees
  add column if not exists pin_enabled boolean not null default true,
  add column if not exists pin_changed_at timestamptz,
  add column if not exists pin_changed_by text,
  add column if not exists terminated_at timestamptz,
  add column if not exists hourly_rate numeric(10,2) not null default 7.00;

create table if not exists public.employee_time_requests (
  id uuid primary key default gen_random_uuid(),
  employee_id uuid not null references public.employees(id) on delete restrict,
  employee_name text not null,
  request_type text not null check (request_type in ('forgotten_entry','forgotten_exit','overtime','other')),
  related_clock_id text null,
  proposed_at timestamptz not null,
  reason text not null,
  status text not null default 'pending' check (status in ('pending','approved','rejected','cancelled')),
  manager_note text,
  reviewed_at timestamptz,
  reviewed_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_employee_time_requests_employee_created
  on public.employee_time_requests(employee_id,created_at desc);
create index if not exists idx_employee_time_requests_status
  on public.employee_time_requests(status,created_at desc);

create table if not exists public.employee_pin_audit (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.employees(id) on delete restrict,
  changed_by text not null check (changed_by in ('employee','manager','system')),
  changed_at timestamptz not null default now(),
  note text
);

create or replace function public.employee_change_own_pin(
  p_employee_id uuid,
  p_current_pin text,
  p_new_pin text
) returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare v_employee public.employees%rowtype;
begin
  if p_new_pin !~ '^\d{4,8}$' then
    raise exception 'El PIN debe tener entre 4 y 8 números';
  end if;
  select * into v_employee from public.employees where id=p_employee_id and active=true;
  if not found or coalesce(v_employee.pin::text,'')<>coalesce(p_current_pin,'') then
    raise exception 'El PIN actual no coincide';
  end if;
  update public.employees set pin=p_new_pin,pin_enabled=true,pin_changed_at=now(),pin_changed_by='employee' where id=p_employee_id;
  insert into public.employee_pin_audit(employee_id,changed_by,note) values(p_employee_id,'employee','Cambio desde Mi Perfil');
  return jsonb_build_object('ok',true);
end;
$$;

grant execute on function public.employee_change_own_pin(uuid,text,text) to anon, authenticated;

-- Mantiene updated_at sin depender de extensiones adicionales.
create or replace function public.colibri_set_updated_at() returns trigger
language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
drop trigger if exists trg_employee_time_requests_updated_at on public.employee_time_requests;
create trigger trg_employee_time_requests_updated_at before update on public.employee_time_requests
for each row execute function public.colibri_set_updated_at();

alter table public.employee_time_requests enable row level security;
alter table public.employee_pin_audit enable row level security;

-- Políticas compatibles con el acceso actual por nombre + PIN del portal piloto.
-- En la futura autenticación individual se sustituirán por políticas ligadas a auth.uid().
drop policy if exists "people requests read" on public.employee_time_requests;
create policy "people requests read" on public.employee_time_requests for select to anon,authenticated using (true);
drop policy if exists "people requests insert" on public.employee_time_requests;
create policy "people requests insert" on public.employee_time_requests for insert to anon,authenticated with check (true);
drop policy if exists "people requests update" on public.employee_time_requests;
create policy "people requests update" on public.employee_time_requests for update to anon,authenticated using (true) with check (true);

drop policy if exists "pin audit manager read" on public.employee_pin_audit;
create policy "pin audit manager read" on public.employee_pin_audit for select to anon,authenticated using (true);

commit;
