-- COLIBRÍ ERP RC 4.1 · Portal completo del empleado
create table if not exists public.employee_time_requests (
  id bigint generated by default as identity primary key,
  employee_id text not null,
  employee_name text not null,
  request_type text not null default 'salida_olvidada',
  proposed_at timestamptz not null,
  reason text not null,
  status text not null default 'pendiente' check (status in ('pendiente','aprobada','rechazada')),
  manager_note text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists employee_time_requests_employee_idx on public.employee_time_requests(employee_id,created_at desc);
alter table public.employee_time_requests enable row level security;
drop policy if exists "employee requests anon read" on public.employee_time_requests;
drop policy if exists "employee requests anon insert" on public.employee_time_requests;
drop policy if exists "employee requests anon update" on public.employee_time_requests;
create policy "employee requests anon read" on public.employee_time_requests for select to anon using (true);
create policy "employee requests anon insert" on public.employee_time_requests for insert to anon with check (true);
create policy "employee requests anon update" on public.employee_time_requests for update to anon using (true) with check (true);
grant select,insert,update on public.employee_time_requests to anon,authenticated;
grant usage,select on sequence public.employee_time_requests_id_seq to anon,authenticated;
